/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CountriesList {
    }
}
declare global {
    interface HTMLCountriesListElement extends Components.CountriesList, HTMLStencilElement {
    }
    var HTMLCountriesListElement: {
        prototype: HTMLCountriesListElement;
        new (): HTMLCountriesListElement;
    };
    interface HTMLElementTagNameMap {
        "countries-list": HTMLCountriesListElement;
    }
}
declare namespace LocalJSX {
    interface CountriesList {
    }
    interface IntrinsicElements {
        "countries-list": CountriesList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "countries-list": LocalJSX.CountriesList & JSXBase.HTMLAttributes<HTMLCountriesListElement>;
        }
    }
}
